Layout/LineLength:
  Max: 120
  Exclude:
    - spec

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/**/*

AllCops:
  Exclude:
    - Gemfile
    - Guardfile
